  services:
    web : 
      image: shokapik
      volumes:
        - ../V5:/var/www/html
        - ../V5:/usr/local/apache2/htdocs
        - ./php:/usr/local/etc/php
        - ./php:/usr/lib/php/extensions/no-debug-non-zts-20230831
        - ./Apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      ports:
        - 8080:80
      networks:
        - app_network
    postgres:
      image: postgres:latest
      restart: always
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      #volumes:
      #  - type: tmpfs
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: test
        POSTGRES_PASSWORD: example
      ports:
        - 5433:5432
      networks:
        - app_network
    pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: adminpassword
      ports:
        - 8081:80
      networks:
        - app_network
  networks:
    app_network:  # Création du réseau
      driver: bridge
      external: true